{% set name = "access" %}
{% set version = "1.1.10.post3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/pysal/access/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7f4ed30a20b4db702d14d46e3adb0677f600823e104207bd4d181731018dab79

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  # The latest geopandas version supports Python 3.13
  skip: true  # [py<311 and py>313]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - toml
  run:
    - python
    - geopandas >=1.0.1
    - numpy >=1.26.0
    - pandas >=2.1.0
    - scipy >=1.14.1

test:
  imports:
    - access
    - access.datasets
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs access
  requires:
    - pip
    - pytest
    - pytest-xdist
    - matplotlib-base
    - scipy >=1.14.1

about:
  home: https://access.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Calculate spatial accessibility metrics
  description: This package provides classical and novel measures of spatial accessibility to services
  doc_url: https://access.readthedocs.io
  dev_url: https://github.com/pysal/access

extra:
  recipe-maintainers:
    - JamesSaxon
    - jkoschinsky
